### PR TITLE
Border sizes

### PR DESCRIPTION
**Pull request by tanc**
As stated in issue #10 the borders are a bit too thick or heavy compared to the GDS ones. This should bring them more inline with the GDS sizes.

### CODE REVIEW

**Comment by tanc** [comment]
From parent font sizes `16px` to `22px` the borders will be `2px` in width, the same as GDS. If the font size is below or above that number the border will scale down or up accordingly.

**Comment by andybroomfield** [comment]
is there a reason to use em and not rem?
That way its possible to use to rem to px trick.
https://snook.ca/archives/html_and_css/font-size-with-rem

**Comment by tanc** [comment]
@andybroomfield I'm not sure, I asked @ekes why `em` rather than pixels, his response:
> The maths there does need recalculating like the px weren't going to apply just so I think, so not knowing what people are going to do I went with 'em' as safer.

I'd be happy with `rem` which is what we use across the site in Lambeth.

**Comment by andybroomfield** [comment]
Thanks @tanc Lets leave it for now. I think we need to have a more through look at theming of localgov_skeleton and how it relates to localgov_theme and where the right styles should apply.

**Comment by finnlewis** [comment]
This is merging into the feature/gds branch - we will need a separate pull request into the master branch.

**Pull request merged**
